version: '3'
services:
  quadratic-equations-service:
    container_name: quadratic-equations
    build: .
    ports:
    - 8281:8281
    depends_on:
    - mongo
    networks:
    - net
    
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - 27017:27017
    networks:
    - net
    
networks:
  net: null
